export const Assets = {
    img1: "./images/img1.jpg",
    img2: "./images/img2.jpg",
    img3: "./images/img3.jpg",
    img4: "./images/img4.jpg",
    img5: "./images/img5.jpg",
    img6: "./images/img6.jpg",
    img7: "./images/img7.jpg",
    flavours: "./images/flavours.png",
    gasvisor: "./images/gasvisor.png",
    mengu: "./images/mengu.png",
    ntopor: "./images/ntopor.png",
    karla: "./images/karla.jpg",
    test1: "./images/test1.jpg",
    test2: "./images/test2.jpg",
    test3: "./images/test3.jpg",
    portfolio: "./images/portfolio.png",
    cv: "./images/cv.pdf",
}